### ISSUE TITLE
Separate searches between English and Toki Pona

### ISSUE THREAD

**Issue by LongJohn-Silver** [jProgr/TokiPonaDictionary#10] opened 2020-11-12 14:50 UTC
I've been using this for a couple of days now while I'm learning, and I got to say that I really like it, but the results aren't that good.

![image](https://user-images.githubusercontent.com/63723030/98954234-7ac12d80-24f5-11eb-9080-dc8ef60b3dcc.png)

Here I searched for "mi", and I get a lot of other results in Toki Pona before I get the word I wanted, simply because one word was first among the English possible results ("coming" in "kama"; "permission" in "ken"; "mineral" in "kiwen"; and so on). I think this maybe could be improved with some hard coding or something, but I still think the results are going to be better and it's going to be much easier to implement if there are two search fields for each language. Maybe in the future, this could help to add even another language to the project, but until that, this is a start.

**Comment by jProgr** [comment] 2020-11-12 15:19
Thanks for pointing it out. This was discussed in the issue #9. The suggested solution was:

> - try to bring first, if exists, the perfect match (ni) for toki pona words
> or highlight if the word searched has a perfect match in the result set.
> - Then add other results

What do you think of the suggestion?

**Comment by LongJohn-Silver** [comment] 2020-11-12 18:13
Pardon me, I skimmed through the issues but I didn't read that from start to finish, so I guess I missed that this is kind of a duplicate.

I still think that the best solution would be to add to search entries for the two languages, as far as I know, this is how every on line dictionary works and even if you would have a ton of resources to improve the algorithm I don't think you'll ever get as good results as if you separate them since there will always be words that share at least one syllable.

This way, if I search for `mi` in the Toki Pona search box, it will appear first `mi`, then `mije` and then `nimi`, since these are the words that have this syllable, and well, English searches will be more clear since there aren't a lot of words with the same meaning.

Maybe instead of two search boxes it could be something like this, with two buttons to select the language: 

![image](https://user-images.githubusercontent.com/63723030/98978969-a1419180-2512-11eb-9f4b-b0fa53d3be46.png)

**Comment by jProgr** [comment] 2020-11-18 15:17
I will close this issue and mark it as duplicate of #9. Let's continue any related conversation there.

**Closed by jProgr** 2020-11-18 15:17 UTC
Labels: duplicate
